config/routes.rb
Rails.application.routes.draw do
  get 'clipchamp-videos', to: 'clipchamp#videos', as: :clipchamp_videos
  get 'clipchamp-videos-show', to: 'clipchamp#video_show', as: :video_show
  get 'clipchamp-photos', to: 'clipchamp#photos', as: :clipchamp_photos
  get 'clipchamp-audios', to: 'clipchamp#audios', as: :clipchamp_audios
  get 'home-image', to: 'home#image', as: :home_image
  get 'flexclip', to: 'flexclip#index', as: :flexclip
  get 'flexclip-download', to: 'flexclip#download', as: :flexclip_download
  get 'public-audio', to: 'public_audio#index', as: :public_audio
  get 'public-photos', to: 'public_photos#index', as: :public_photos
  get 'unsplash', to: 'public_photos#unsplash', as: :unsplash
  get 'invideo', to: 'invideo#index', as: :invideo
  get 'invideo-download', to: 'invideo#download', as: :invideo_download
  get 'collected-blogs', to: 'collected_blogs#index', as: :collected_blogs
  get 'youtube-channels', to: 'collected_blogs#youtube_channel', as: :youtube_channel
  get 'useful-links', to: 'collected_blogs#useful_links', as: :useful_links
  get 'lumen', to: 'lumen#index', as: :lumen
  get 'promo', to: 'promo#index', as: :promo
  get 'promo-photos', to: 'promo#photos', as: :promo_photos
  get 'powton', to: 'powton#index', as: :powton
  get 'powton-download', to: 'powton#download', as: :powton_download
  get 'my-visme', to: 'my_visme#index', as: :my_visme
  get 'my-visme-download', to: 'my_visme#download', as: :my_visme_download
  get 'home/test'
  get 'unblock-site', to: 'unblock_site#index', as: :unblock_site
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'temporary-phone-number', to: 'temporary_phone_number#index', as: :temporary_phone_number
  get 'temporary-phone-number/inbox', to: 'temporary_phone_number#inbox', as: :temporary_phone_number_inbox
  get 'fake-address-generator', to: 'fake_address_generator#index', as: :fake_address_generator
  get 'youtube-tag-extractor', to: 'youtube_tag_extractor#index', as: :youtube_tag_extractor
  get 'apk_download/index'
  get 'ubersuggest', to: 'ubersuggest#index', as: :ubersuggest
  get 'youtube_downloader', to: 'youtube_downloader#index', as: :youtube_downloader
  get 'tempmail', to: 'tempmail#index', as: :tempmail
  get 'change-mail', to: 'tempmail#change_mail', as: :change_mail
  get 'image/new'
  post 'image/create', as: :image
  get 'storyblocks', to: 'storyblocks#index', as: :storyblocks
  get 'storyblocks_photos', to: 'storyblocks#photos', as: :storyblocks_photos
  get 'jumpstory', to: 'jumpstory#index', as: :jumpstory
  get 'jumpstory-photos', to: 'jumpstory#photos', as: :jumpstory_photos
  get 'keyword-research', to: 'keyword_research#index', as: :keyword_research
  get 'shutterstock-videos', to: 'shutterstock_videos#index', as: :shutterstock_videos
  get 'shutterstock-video-details', to: 'shutterstock_videos#details', as: :shutterstock_videos_details
  get 'shutterstock-photos', to: 'shutterstock_photos#index', as: :shutterstock_photos
  get 'shutterstock_photo_details', to: 'shutterstock_photos#details', as: :shutterstock_photos_details
  get 'wevideo', to: 'wevideo#index', as: 'wevideo'
  get 'biteable', to: 'biteable#index', as: 'biteable'
  get 'biteable-photos', to: 'biteable#photos', as: 'biteable_photos'
  get 'vidnami', to: 'vidnami#index', as: 'vidnami'
  get 'download', to: 'vidnami#download', as: 'download'
  get 'vidnami-token', to: 'vidnami#vidnami_token'
  get 'home/index'
  get 'home/download'
  get 'home/confirm', as: 'confirm'
  root 'home#index'
  get 'home/links', as: 'links'
end

app/views/layouts/shared/_nav.html.erb
<nav class="navbar navbar-default" id="top-nav">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to 'Home', root_path, class: 'navbar-brand'%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= nav_active('home', 'index') %>">
          <%= link_to nav_query_path(root_path) do %>
            Supa
          <% end %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Footage <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Storyblocks Footage', nav_query_path(storyblocks_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Bitable Video', nav_query_path(biteable_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Shutterstock Videos', nav_query_path(shutterstock_videos_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Jumpstory', nav_query_path(jumpstory_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Vidnami', nav_query_path(vidnami_path) %> </li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'My Visme', nav_query_path(my_visme_path) %> </li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Powton', nav_query_path(powton_path) %> </li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Promo', nav_query_path(promo_path) %> </li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Lumen', nav_query_path(lumen_path) %> </li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'InVideo iStock', nav_query_path(invideo_path) %> </li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Flexclip storyblocks', nav_query_path(flexclip_path) %> </li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Wevideo', nav_query_path(wevideo_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Clipchamp', nav_query_path(clipchamp_videos_path) %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Photos <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Storyblocks Photos', nav_query_path(storyblocks_photos_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Bitable Photos', nav_query_path(biteable_photos_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Shutterstock Photos', nav_query_path(shutterstock_photos_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Jumpstory Photos', nav_query_path(jumpstory_photos_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Promo getty Photos', nav_query_path(promo_photos_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Animoto getty Photos', nav_query_path(public_photos_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Unsplash', nav_query_path(unsplash_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Home Image Gallery', nav_query_path(home_image_path) %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Audio <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Invideo audio', nav_query_path(public_audio_path) %></li>
            <li role="separator" class="divider"></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tools <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Youtube Downloader', youtube_downloader_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Tempmail', tempmail_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Keyword research', keyword_research_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Ubersuggest', keyword_research_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'YouTube Tag Extractor', youtube_tag_extractor_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Fake Address Generator', fake_address_generator_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Temporary Phone Number', temporary_phone_number_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Unblock Site', unblock_site_path %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Resources <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Blog and News', collected_blogs_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Youtube channel', youtube_channel_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Useful Links', useful_links_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Maya Links', links_path %></li>
          </ul>
        </li>
      </ul>

      <%= render 'layouts/shared/search' %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<script type="text/javascript" charset="utf-8">
    var lastScrollTop = 0;
    $(window).scroll(function(event){
        var st = $(this).scrollTop();
        if (st == 0){
            $("#top-nav" ).removeClass("navbar-fixed-top box-shadow" );
        } else {
            $("#top-nav" ).addClass( "navbar-fixed-top box-shadow" );
        }
        lastScrollTop = st;
    });
</script>

app/views/layouts/shared/_search.html.erb
<% unless controller.controller_name=='youtube_downloader' || controller.controller_name=='tempmail'%>
  <%= form_with url: url_path, method: :get, data: { turbolinks: false }, class: 'navbar-form navbar-left' do |form| %>
    <div class="form-group">
      <%= form.text_field :query, value: params[:query], placeholder: 'Search', class: "form-control" %>
    </div>

    <% if controller.controller_name=='wevideo' %>
      <div class="form-group">
        <%= select_tag("type", options_for_select(AppSetting::TYPE, params[:type]), class: "form-control")%>
      </div>
    <% end %>

    <% if controller.controller_name=='powton' %>
      <div class="form-group">
        <%= hidden_field_tag(:blocks_type, params[:blocks_type])%>
      </div>
    <% end %>

    <%= form.submit "Search", class: 'btn btn-default' %>
  <% end %>
<% end %>

<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><a href="#"><%= current_user.email %></a></li>
      <li role="separator" class="divider"></li>
      <li><%= link_to('Logout', destroy_user_session_path, :method => :delete)  %></li>

    </ul>
  </li>
</ul>