config/routes.rb
Rails.application.routes.draw do
  get 'clipchamp-videos', to: 'clipchamp#videos', as: :clipchamp_videos
  get 'clipchamp-videos-show', to: 'clipchamp#video_show', as: :video_show
  get 'clipchamp-photos', to: 'clipchamp#photos', as: :clipchamp_photos
  get 'clipchamp-audios', to: 'clipchamp#audios', as: :clipchamp_audios
  get 'home-image', to: 'home#image', as: :home_image
  get 'flexclip', to: 'flexclip#index', as: :flexclip
  get 'flexclip-download', to: 'flexclip#download', as: :flexclip_download
  get 'public-audio', to: 'public_audio#index', as: :public_audio
  get 'public-photos', to: 'public_photos#index', as: :public_photos
  get 'unsplash', to: 'public_photos#unsplash', as: :unsplash
  get 'invideo', to: 'invideo#index', as: :invideo
  get 'invideo-download', to: 'invideo#download', as: :invideo_download
  get 'collected-blogs', to: 'collected_blogs#index', as: :collected_blogs
  get 'youtube-channels', to: 'collected_blogs#youtube_channel', as: :youtube_channel
  get 'useful-links', to: 'collected_blogs#useful_links', as: :useful_links
  get 'lumen', to: 'lumen#index', as: :lumen
  get 'promo', to: 'promo#index', as: :promo
  get 'promo-photos', to: 'promo#photos', as: :promo_photos
  get 'powton', to: 'powton#index', as: :powton
  get 'powton-download', to: 'powton#download', as: :powton_download
  get 'my-visme', to: 'my_visme#index', as: :my_visme
  get 'my-visme-download', to: 'my_visme#download', as: :my_visme_download
  get 'home/test'
  get 'unblock-site', to: 'unblock_site#index', as: :unblock_site
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'temporary-phone-number', to: 'temporary_phone_number#index', as: :temporary_phone_number
  get 'temporary-phone-number/inbox', to: 'temporary_phone_number#inbox', as: :temporary_phone_number_inbox
  get 'fake-address-generator', to: 'fake_address_generator#index', as: :fake_address_generator
  get 'youtube-tag-extractor', to: 'youtube_tag_extractor#index', as: :youtube_tag_extractor
  get 'apk_download/index'
  get 'ubersuggest', to: 'ubersuggest#index', as: :ubersuggest
  get 'youtube_downloader', to: 'youtube_downloader#index', as: :youtube_downloader
  get 'tempmail', to: 'tempmail#index', as: :tempmail
  get 'change-mail', to: 'tempmail#change_mail', as: :change_mail
  get 'image/new'
  post 'image/create', as: :image
  get 'storyblocks', to: 'storyblocks#index', as: :storyblocks
  get 'storyblocks_photos', to: 'storyblocks#photos', as: :storyblocks_photos
  get 'jumpstory', to: 'jumpstory#index', as: :jumpstory
  get 'jumpstory-photos', to: 'jumpstory#photos', as: :jumpstory_photos
  get 'keyword-research', to: 'keyword_research#index', as: :keyword_research
  get 'shutterstock-videos', to: 'shutterstock_videos#index', as: :shutterstock_videos
  get 'shutterstock-video-details', to: 'shutterstock_videos#details', as: :shutterstock_videos_details
  get 'shutterstock-photos', to: 'shutterstock_photos#index', as: :shutterstock_photos
  get 'shutterstock_photo_details', to: 'shutterstock_photos#details', as: :shutterstock_photos_details
  get 'wevideo', to: 'wevideo#index', as: 'wevideo'
  get 'biteable', to: 'biteable#index', as: 'biteable'
  get 'biteable-photos', to: 'biteable#photos', as: 'biteable_photos'
  get 'vidnami', to: 'vidnami#index', as: 'vidnami'
  get 'download', to: 'vidnami#download', as: 'download'
  get 'vidnami-token', to: 'vidnami#vidnami_token'
  get 'home/index'
  get 'home/download'
  get 'home/confirm', as: 'confirm'
  root 'home#index'
  get 'home/links', as: 'links'
end

app/controllers/shutterstock_videos_controller.rb
class ShutterstockVideosController < ApplicationController
  require 'net/http'
  require 'open-uri'

  def index
    @page = params[:page].present? ? params[:page] : 1
    if params[:query].present?
      uri = URI("https://api.ripl.com/stock_media/search/videos.json?auth_token=Yiim7WgHst4LFXPmucyL&page=#{@page}&query=#{params[:query]}")
    else
      uri = URI("https://api.ripl.com/stock_media/search/videos.json?auth_token=Yiim7WgHst4LFXPmucyL&page=#{@page}")
    end
    
    res = Net::HTTP.get_response(uri)
    @res = JSON.parse(res.body)

    respond_to do |format|
      format.html
      format.json { render json: {res: @res} }
    end
  end

  def details
    uri = URI("https://api.ripl.com/stock_media/video.json?auth_token=Yiim7WgHst4LFXPmucyL&external_media_id=#{params[:media]}")
    res = Net::HTTP.get_response(uri)
    @res = JSON.parse(res.body)
    render layout: "download"
  end
end

app/views/shutterstock_videos/details.html.erb
<div style="margin: auto; text-align: center">
  <%= link_to 'Download', @res['url'], class: 'btn btn-primary', style: "width: 470px; height: 150px; font-size: 100px", target: '_blank', :onclick=> "window.close();"%>
</div>

app/views/shutterstock_videos/index.html.erb
<div class="row video-class">
  <% @res['matches'].each do |data| %>
    <%= link_to shutterstock_videos_details_path(media: data['external_media_id']),'data-popup' => true, :onclick=>"window.open(this.href,'quick_help', 'height=300, width=500'); return false;" do %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail" style="height: 220px">
          <%= image_tag(data['thumbnail_url'], size: '320x180')%>
          <br>
          <p style="font-size: 12px; text-align: center">
            Click here for Download the video
          </p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>


<script type="text/javascript">
    var page = 2;
    $(window).scroll(function() {
        if($(window).scrollTop() + $(window).height() >= $(document).height()) {
            var lastId = $(".well:last").attr("id");
            $.ajax({
                url: `<%= "#{url_path}?query=#{params[:query]}"%>&page=${page}`,
                type: "get",
                dataType: "json",
                beforeSend: function (){
                    $('.ajax-loader').show();
                },
                success: function (data) {
                    for (let i = 0; i < data['res']['matches'].length; i++) {
                        htm = `
                                <a data-popup="true" onclick="window.open(this.href,'quick_help', 'height=300, width=500'); return false;" href="/shutterstock_video_details?media=${data['res']['matches'][i]['external_media_id']}">
                                  <div class="col-sm-6 col-md-3">
                                    <div class="thumbnail" style="height: 220px">
                                      <img src="${data['res']['matches'][i]['thumbnail_url']}" style="width: 320px; height: 180px">
                                      <br>
                                      <p style="font-size: 12px; text-align: center">
                                          Click here for Download the video
                                      </p>
                                    </div>
                                  </div>
                                </a>
                              `
                        $(".video-class").append(htm);
                    }
                    page++;
                }
            });
        }
    });
</script>