config/routes.rb
Rails.application.routes.draw do
  get 'clipchamp-videos', to: 'clipchamp#videos', as: :clipchamp_videos
  get 'clipchamp-videos-show', to: 'clipchamp#video_show', as: :video_show
  get 'clipchamp-photos', to: 'clipchamp#photos', as: :clipchamp_photos
  get 'clipchamp-audios', to: 'clipchamp#audios', as: :clipchamp_audios
  get 'home-image', to: 'home#image', as: :home_image
  get 'flexclip', to: 'flexclip#index', as: :flexclip
  get 'flexclip-download', to: 'flexclip#download', as: :flexclip_download
  get 'public-audio', to: 'public_audio#index', as: :public_audio
  get 'public-photos', to: 'public_photos#index', as: :public_photos
  get 'unsplash', to: 'public_photos#unsplash', as: :unsplash
  get 'invideo', to: 'invideo#index', as: :invideo
  get 'invideo-download', to: 'invideo#download', as: :invideo_download
  get 'collected-blogs', to: 'collected_blogs#index', as: :collected_blogs
  get 'youtube-channels', to: 'collected_blogs#youtube_channel', as: :youtube_channel
  get 'useful-links', to: 'collected_blogs#useful_links', as: :useful_links
  get 'lumen', to: 'lumen#index', as: :lumen
  get 'promo', to: 'promo#index', as: :promo
  get 'promo-photos', to: 'promo#photos', as: :promo_photos
  get 'powton', to: 'powton#index', as: :powton
  get 'powton-download', to: 'powton#download', as: :powton_download
  get 'my-visme', to: 'my_visme#index', as: :my_visme
  get 'my-visme-download', to: 'my_visme#download', as: :my_visme_download
  get 'home/test'
  get 'unblock-site', to: 'unblock_site#index', as: :unblock_site
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'temporary-phone-number', to: 'temporary_phone_number#index', as: :temporary_phone_number
  get 'temporary-phone-number/inbox', to: 'temporary_phone_number#inbox', as: :temporary_phone_number_inbox
  get 'fake-address-generator', to: 'fake_address_generator#index', as: :fake_address_generator
  get 'youtube-tag-extractor', to: 'youtube_tag_extractor#index', as: :youtube_tag_extractor
  get 'apk_download/index'
  get 'ubersuggest', to: 'ubersuggest#index', as: :ubersuggest
  get 'youtube_downloader', to: 'youtube_downloader#index', as: :youtube_downloader
  get 'tempmail', to: 'tempmail#index', as: :tempmail
  get 'change-mail', to: 'tempmail#change_mail', as: :change_mail
  get 'image/new'
  post 'image/create', as: :image
  get 'storyblocks', to: 'storyblocks#index', as: :storyblocks
  get 'storyblocks_photos', to: 'storyblocks#photos', as: :storyblocks_photos
  get 'jumpstory', to: 'jumpstory#index', as: :jumpstory
  get 'jumpstory-photos', to: 'jumpstory#photos', as: :jumpstory_photos
  get 'keyword-research', to: 'keyword_research#index', as: :keyword_research
  get 'shutterstock-videos', to: 'shutterstock_videos#index', as: :shutterstock_videos
  get 'shutterstock-video-details', to: 'shutterstock_videos#details', as: :shutterstock_videos_details
  get 'shutterstock-photos', to: 'shutterstock_photos#index', as: :shutterstock_photos
  get 'shutterstock_photo_details', to: 'shutterstock_photos#details', as: :shutterstock_photos_details
  get 'wevideo', to: 'wevideo#index', as: 'wevideo'
  get 'biteable', to: 'biteable#index', as: 'biteable'
  get 'biteable-photos', to: 'biteable#photos', as: 'biteable_photos'
  get 'vidnami', to: 'vidnami#index', as: 'vidnami'
  get 'download', to: 'vidnami#download', as: 'download'
  get 'vidnami-token', to: 'vidnami#vidnami_token'
  get 'home/index'
  get 'home/download'
  get 'home/confirm', as: 'confirm'
  root 'home#index'
  get 'home/links', as: 'links'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'net/http'
  require 'open-uri'

  def index
    @page = params[:page].present? ? params[:page] : 1
    limit = 30
    uri = URI("https://api.supa.ru/library/video?service=storyblocks&page=#{@page}&limit=#{limit}&search=#{params[:query]}&content_type=footage") if params[:query].present?
    uri = URI("https://api.supa.ru/library/video?service=storyblocks&page=#{@page}&limit=#{limit}&content_type=footage") unless params[:query].present?
    res = Net::HTTP.get_response(uri)
    @res = JSON.parse(res.body)
    respond_to do |format|
        format.html
        format.json { render json: {res: @res} }
    end
  end

  def image
    @res = Biteable::Photos.search(params[:page], params[:query], 30)
    render layout: "image"
  end

  def download
    uri = URI("https://api.supa.ru/library/resource?id=#{params[:id]}&service=#{params[:service]}")
    res = Net::HTTP.get_response(uri)
    @res = JSON.parse(res.body)

    unless @res.present?
      respond_to do |format|
        format.html { redirect_to request.url, notice: 'page was successfully reload.' }
        format.json { head :no_content }
      end
    end

    uri2 = URI('https://api.supa.ru/cropper-helper/preview')
    res2 = Net::HTTP.post_form(uri2, 'video_url' => @res['url'], 'frames' => 10, 'frames_width' => 168, 'cache' => true)
    @res2 = JSON.parse(res2.body)
    render layout: "download"
  end

  def confirm
    @res = url_call(params[:task_id])
    @result = @res['source_original']['url']
    render layout: "download"
  end

  def links

  end

  def test
    @source = open("https://youtube.com").read
  end

  private 
  def url_call(task_id)
    uri = URI("https://api.supa.ru/cropper-helper/task/#{params[:task_id]}")
    res = Net::HTTP.get_response(uri)
    result = JSON.parse(res.body)
    if result['state'] == "done"
      return result
    else
      url_call(task_id)
    end
  end
end

app/views/home/_image_data.html.erb
<% images.each do |img| %>
  <%= image_tag(img['urls']['thumb'], style: 'width: 400px')%>
<% end %>

app/views/home/confirm.html.erb
<div style="margin: auto; text-align: center">
  <%= link_to 'Download', @result, class: 'btn btn-primary', style: "width: 470px; height: 150px; font-size: 100px", target: '_blank', :onclick=> "window.close();"%>
</div>

app/views/home/download.html.erb
<div style="margin: auto; text-align: center">
    <%= link_to 'confirm', confirm_path(task_id: @res2['task_id']), class: 'btn btn-primary', style: "width: 400px; height: 150px; font-size: 100px"%>
</div>

app/views/home/image.html.erb
<div class="container">
  <div class="heading">
    <h3>Photo <span>Galary</span></h3>
  </div>
  <div class="box">
    <div class="dream" id="dream-1">
      <%= render 'image_data', images: @res['results'].first(10) %>
    </div>
    <div class="dream" id="dream-2">
      <%= render 'image_data', images: @res['results'].first(20).last(10) %>
    </div>
    <div class="dream" id="dream-3">
      <%= render 'image_data', images: @res['results'].first(30).last(10) %>
    </div>
  </div>
  <div class="btn">
    <button onclick="load_more()">More</button>
  </div>

  <script type="text/javascript" charset="utf-8">
      var page = 2
      function load_more() {
          $.ajax({
              url: `<%= "#{url_path}?query=#{params[:query]}"%>&page=${page}`,
              type: "get",
              dataType: "script",
              beforeSend: function (){
                  $('.ajax-loader').show();
              },
              success: function (data) {
                  console.log('success');
              }
          });
      }
  </script>
</div>

app/views/home/image.js.erb
$("#dream-1").append("<%= escape_javascript(render 'image_data', images: @res['results'].first(10)).html_safe %>");
$("#dream-2").append("<%= escape_javascript(render 'image_data', images: @res['results'].first(20).last(10)).html_safe %>");
$("#dream-3").append("<%= escape_javascript(render 'image_data', images: @res['results'].first(30).last(10)).html_safe %>");
page++;

app/views/home/index.html.erb
<div class="row video-class">
  <% @res['docs'].each do |res| %>
    <%= link_to("home/download?id=#{res['id']}&service=storyblocks",'data-popup' => true, :onclick=>"window.open(this.href,'quick_help', 'height=300, width=500'); return false;") do%>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail" style="height: 220px">
          <%= image_tag(res['previewURL'])%>
          <br>
          <p style="font-size: 12px; text-align: center">
            <%= truncate(res['item']['title'], length:35)  %>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<script type="text/javascript">
    var page = 2;
    $(window).scroll(function() {
        if($(window).scrollTop() + $(window).height() >= $(document).height()) {
            var lastId = $(".well:last").attr("id");
            $.ajax({
                url: `<%= "#{url_path}?query=#{params[:query]}"%>&page=${page}`,
                type: "get",
                dataType: "json",
                beforeSend: function (){
                    $('.ajax-loader').show();
                },
                success: function (data) {
                    for (let i = 0; i < data['res']['docs'].length; i++) {
                        htm = `
                                <a data-popup="true" onclick="window.open(this.href,'quick_help', 'height=300, width=500'); return false;" href="home/download?id=${data['res']['docs'][i]['id']}&amp;service=storyblocks">
                                  <div class="col-sm-6 col-md-3">
                                    <div class="thumbnail" style="height: 220px">
                                      <img src="${data['res']['docs'][i]['previewURL']}">
                                      <br>
                                      <p style="font-size: 12px; text-align: center">
                                          ${data['res']['docs'][i]['item']['title'].substring(0, 35)}
                                      </p>
                                    </div>
                                  </div>
                                </a>
                              `
                        $(".video-class").append(htm);
                    }
                    page++;
                }
            });
        }
    });
</script>

app/views/home/links.html.erb
<h2>Mayajaal video resource Link</h2>
<%= link_to 'Home', root_path %>
<hr>
<div class="col-md-6">
  <h4>Top free stock footage sites by Team Mayajaal</h4>
  <p>
    <%= link_to 'Dareful', 'http://www.dareful.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'videvo', 'http://www.videvo.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'pixabay', 'http://www.pixabay.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'lifeofvids', 'http://www.lifeofvids.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'pexels', 'http://www.pexels.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'isorepublic', 'http://www.isorepublic.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'mazwai', 'http://www.mazwai.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'videvonet', 'http://www.videvonet.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'stocksy', 'http://www.stocksy.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'videoblocks', 'http://www.videoblocks.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'dareful', 'http://www.dareful.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'wedistill', 'http://www.wedistill.io', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'coverr', 'http://www.coverr.co', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'videvo', 'http://www.videvo.net', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'stockfootageforfree', 'http://www.stockfootageforfree.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'cutestockfootage', 'http://www.cutestockfootage.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'pikwizard', 'http://www.pikwizard.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'isorepublic', 'http://www.isorepublic.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'focastock', 'http://www.focastock.com', target: '_blank'%>
  </p>

</div>

<div class="col-md-6">
  <h4>Top premium stock footage sites by Team Mayajaal</h4>
  <p>
    <%= link_to 'videezy', 'http://www.videezy.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'flickr', 'www.flickr.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'morguefile', 'http://www.morguefile.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'bigstockphoto', 'http://www.bigstockphoto.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'dissolve', 'http://www.dissolve.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'filmsupply', 'http://www.filmsupply.com', target: '_blank'%>
  </p>


  <p>
    <%= link_to 'rocketstock', 'http://www.rocketstock.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to '123rf', 'http://www.123rf.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'www.pond5.com/stock-footage/', 'http://www.pond5.com/stock-footage/', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'storyandheart', 'http://www.storyandheart.com', target: '_blank'%>
  </p>

  <p>
    <%= link_to 'clipstill', 'http://www.clipstill.com', target: '_blank'%>
  </p>

</div>

app/views/home/test.html.erb
<%= raw @source %>