config/routes.rb
Rails.application.routes.draw do
  get 'clipchamp-videos', to: 'clipchamp#videos', as: :clipchamp_videos
  get 'clipchamp-videos-show', to: 'clipchamp#video_show', as: :video_show
  get 'clipchamp-photos', to: 'clipchamp#photos', as: :clipchamp_photos
  get 'clipchamp-audios', to: 'clipchamp#audios', as: :clipchamp_audios
  get 'home-image', to: 'home#image', as: :home_image
  get 'flexclip', to: 'flexclip#index', as: :flexclip
  get 'flexclip-download', to: 'flexclip#download', as: :flexclip_download
  get 'public-audio', to: 'public_audio#index', as: :public_audio
  get 'public-photos', to: 'public_photos#index', as: :public_photos
  get 'unsplash', to: 'public_photos#unsplash', as: :unsplash
  get 'invideo', to: 'invideo#index', as: :invideo
  get 'invideo-download', to: 'invideo#download', as: :invideo_download
  get 'collected-blogs', to: 'collected_blogs#index', as: :collected_blogs
  get 'youtube-channels', to: 'collected_blogs#youtube_channel', as: :youtube_channel
  get 'useful-links', to: 'collected_blogs#useful_links', as: :useful_links
  get 'lumen', to: 'lumen#index', as: :lumen
  get 'promo', to: 'promo#index', as: :promo
  get 'promo-photos', to: 'promo#photos', as: :promo_photos
  get 'powton', to: 'powton#index', as: :powton
  get 'powton-download', to: 'powton#download', as: :powton_download
  get 'my-visme', to: 'my_visme#index', as: :my_visme
  get 'my-visme-download', to: 'my_visme#download', as: :my_visme_download
  get 'home/test'
  get 'unblock-site', to: 'unblock_site#index', as: :unblock_site
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'temporary-phone-number', to: 'temporary_phone_number#index', as: :temporary_phone_number
  get 'temporary-phone-number/inbox', to: 'temporary_phone_number#inbox', as: :temporary_phone_number_inbox
  get 'fake-address-generator', to: 'fake_address_generator#index', as: :fake_address_generator
  get 'youtube-tag-extractor', to: 'youtube_tag_extractor#index', as: :youtube_tag_extractor
  get 'apk_download/index'
  get 'ubersuggest', to: 'ubersuggest#index', as: :ubersuggest
  get 'youtube_downloader', to: 'youtube_downloader#index', as: :youtube_downloader
  get 'tempmail', to: 'tempmail#index', as: :tempmail
  get 'change-mail', to: 'tempmail#change_mail', as: :change_mail
  get 'image/new'
  post 'image/create', as: :image
  get 'storyblocks', to: 'storyblocks#index', as: :storyblocks
  get 'storyblocks_photos', to: 'storyblocks#photos', as: :storyblocks_photos
  get 'jumpstory', to: 'jumpstory#index', as: :jumpstory
  get 'jumpstory-photos', to: 'jumpstory#photos', as: :jumpstory_photos
  get 'keyword-research', to: 'keyword_research#index', as: :keyword_research
  get 'shutterstock-videos', to: 'shutterstock_videos#index', as: :shutterstock_videos
  get 'shutterstock-video-details', to: 'shutterstock_videos#details', as: :shutterstock_videos_details
  get 'shutterstock-photos', to: 'shutterstock_photos#index', as: :shutterstock_photos
  get 'shutterstock_photo_details', to: 'shutterstock_photos#details', as: :shutterstock_photos_details
  get 'wevideo', to: 'wevideo#index', as: 'wevideo'
  get 'biteable', to: 'biteable#index', as: 'biteable'
  get 'biteable-photos', to: 'biteable#photos', as: 'biteable_photos'
  get 'vidnami', to: 'vidnami#index', as: 'vidnami'
  get 'download', to: 'vidnami#download', as: 'download'
  get 'vidnami-token', to: 'vidnami#vidnami_token'
  get 'home/index'
  get 'home/download'
  get 'home/confirm', as: 'confirm'
  root 'home#index'
  get 'home/links', as: 'links'
end

app/controllers/powton_controller.rb
class PowtonController < ApplicationController
  require "uri"
  require "json"
  require "net/http"

  def index
    blocks_type = params[:blocks_type].present? ? params[:blocks_type] : 'storyblocks'
    @page = params[:page].present? ? params[:page] : 1
    url = URI("https://powtoon-api-1.global.ssl.fastly.net/api/v2/media-catalog/providers/#{blocks_type}?search=#{params[:query]}&page_size=99&page=#{@page}")
    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true
    request = Net::HTTP::Get.new(url)
    response = https.request(request)
    @res = JSON.parse(response.read_body)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def download
    blocks_type = params[:blocks_type].present? ? params[:blocks_type] : 'storyblocks'
    url = URI("https://www.powtoon.com/api/v2/media-catalog/providers/#{blocks_type}")
    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true
    request = Net::HTTP::Post.new(url)
    request["x-csrftoken"] = ENV['POWTON_X_CSRFTOKEN']
    request["cookie"] = ENV['POWTON_COOKIE']
    request["referer"] = ENV['POWTON_REFERER']
    request["Content-Type"] = "application/json"
    request.body = JSON.dump({
                               "provider_id": params[:video_info][:provider_id],
                               "width": params[:video_info][:width],
                               "height": params[:video_info][:height],
                               "item_type": params[:video_info][:item_type],
                               "file_format": params[:video_info][:file_format],
                               "thumb_url": params[:video_info][:thumb_url],
                               "preview_url": params[:video_info][:preview_url],
                               "file_url": params[:video_info][:file_url],
                               "name": params[:video_info][:name],
                               "description": params[:video_info][:description],
                               "license_level": params[:video_info][:license_level],
                               "families": params[:video_info][:families],
                               "duration": 10,
                               "video_data": {
                                 "original_duration": 10,
                                 "duration": 10,
                                 "video_files": {
                                   "preview": params[:video_info][:video_data][:video_files][:preview]
                                 }
                               },
                               "provider": params[:video_info][:provider],
                               "item_name": params[:video_info][:item_name],
                               "items_name": params[:video_info][:items_name],
                               "id": params[:video_info][:id]
                             })

    response = https.request(request)
    @res = JSON.parse(response.read_body)
    render layout: "download"
  end

  private
  def video_params
    params.require(:video_info).permit!
  end
end

app/helpers/powton_helper.rb
module PowtonHelper
end

app/views/powton/_data.html.erb
<% @res['results'].each do |res| %>
  <%= link_to(powton_download_path(video_info: res, blocks_type: params[:blocks_type]), 'data-popup' => true, :onclick=>"window.open(this.href,'quick_help', 'height=300, width=500'); return false;") do%>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail" style="height: 220px">
        <%= image_tag(res['thumb_url'])%>
        <br>
        <p style="font-size: 12px; text-align: center">
          <%= truncate(res['name'], length:35)  %>
        </p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/powton/download.html.erb
<div style="margin: auto; text-align: center">
  <%= link_to 'Download', @res['data_url'], class: 'btn btn-primary', style: "width: 470px; height: 150px; font-size: 100px", target: '_blank', :onclick=> "window.close();"%>
</div>

app/views/powton/index.html.erb
<div class="btn-group" role="group" aria-label="...">
  <%= link_to 'Storyblocks', powton_path(blocks_type: 'storyblocks', query: params[:query]), class: "btn btn-default" %>
  <%= link_to 'Technologystoryblocks', powton_path(blocks_type: 'technologystoryblocks', query: params[:query]), class: "btn btn-default" %>
  <%= link_to 'Businessstoryblocks', powton_path(blocks_type: 'businessstoryblocks', query: params[:query]), class: "btn btn-default" %>
  <%= link_to 'Holidaysstoryblocks', powton_path(blocks_type: 'holidaysstoryblocks', query: params[:query]), class: "btn btn-default" %>
  <%= link_to 'Naturestoryblocks', powton_path(blocks_type: 'naturestoryblocks', query: params[:query]), class: "btn btn-default" %>
  <%= link_to 'Peoplestoryblocks', powton_path(blocks_type: 'peoplestoryblocks', query: params[:query]), class: "btn btn-default" %>
</div>
<br>
<br>
<div class="row video-class">
  <% @res['results'].each do |res| %>
    <%= link_to(powton_download_path(video_info: res, blocks_type: params[:blocks_type]), 'data-popup' => true, :onclick=>"window.open(this.href,'quick_help', 'height=300, width=500'); return false;") do%>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail" style="height: 220px">
          <%= image_tag(res['thumb_url'])%>
          <br>
          <p style="font-size: 12px; text-align: center">
            <%= truncate(res['name'], length:35)  %>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<script type="text/javascript">
    var page = 2;
    $(window).scroll(function() {
        if($(window).scrollTop() + $(window).height() >= $(document).height()) {
            var lastId = $(".well:last").attr("id");
            $.ajax({
                url: `<%= "#{url_path}?query=#{params[:query]}&blocks_type=#{params[:blocks_type]}"%>&page=${page}`,
                type: "get",
                dataType: "script",
                beforeSend: function (){
                    $('.ajax-loader').show();
                },
                success: function (data) {
                    page++;
                }
            });
        }
    });
</script>

app/views/powton/index.js.erb
$(".video-class").append("<%= escape_javascript(render 'data').html_safe %>");